"""Add workflow details

Revision ID: 3792c6336a1c
Revises: 304d94da6fbe
Create Date: 2026-07-03 11:12:01.130052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3792c6336a1c'
down_revision: Union[str, Sequence[str], None] = '304d94da6fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyers', sa.Column('reliability_score', sa.Integer(), nullable=True))
    op.add_column('contracts', sa.Column('eway_bill', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('gps_tracking_id', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('gst_invoice', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('grn_number', sa.String(), nullable=True))
    op.add_column('fpos', sa.Column('reliability_score', sa.Integer(), nullable=True))
    op.add_column('lots', sa.Column('variety', sa.String(), nullable=True))
    op.add_column('lots', sa.Column('curcumin', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('lots', sa.Column('harvest_date', sa.DateTime(), nullable=True))
    op.add_column('lots', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('lots', sa.Column('lab_report_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lots', 'lab_report_url')
    op.drop_column('lots', 'notes')
    op.drop_column('lots', 'harvest_date')
    op.drop_column('lots', 'curcumin')
    op.drop_column('lots', 'variety')
    op.drop_column('fpos', 'reliability_score')
    op.drop_column('contracts', 'grn_number')
    op.drop_column('contracts', 'gst_invoice')
    op.drop_column('contracts', 'gps_tracking_id')
    op.drop_column('contracts', 'eway_bill')
    op.drop_column('buyers', 'reliability_score')
    # ### end Alembic commands ###
